[scalert] allow filtering on streamID for pick script
SeisComP/main pull request #43
Opened 2022-09-01 10:02 UTC by luca-s

This PR adds a configuration option that allows to filter the picks for which the pick script is called based on the pick streamID.

2022-09-01 10:54 UTC, gempa-dirk commented on apps/python/descriptions/scalert.xml
> +					of the received	pick belongs to the list. If empty, all picks
Remove double spaces

2022-09-01 10:55 UTC, gempa-dirk commented on apps/python/scalert.py
> +                    seiscomp.logging.error("Wrong wafeformid in `constraints.phaseStreams`: %s" % item)
wafeformid -> stream ID (not wafe!)

2022-09-01 11:00 UTC, gempa-dirk requested changes

2022-09-01 11:00 UTC, gempa-dirk commented on apps/python/scalert.py
> +            seiscomp.logging.info(" + phase waveformid filter for picks: '%s'" % (" ".join(self._phaseStreams)))
waveformid -> waveform ID, write capitals for abbreviations and separate them.

2022-09-01 11:00 UTC, gempa-dirk commented on apps/python/scalert.py
> +            seiscomp.logging.info(" + phase waveformid filter for picks: '%s'" % (" ".join(self._phaseStreams)))
stream ID instead of waveformid

2022-09-01 11:00 UTC, gempa-dirk commented on apps/python/scalert.py
> +                                " + waveformID %s does not match constraints.phaseStreams rules"
stream ID

2022-09-01 11:05 UTC, luca-s commented
Thanks for reviewing @gempa-dirk. I fixed the issues

2022-09-03 09:59 UTC, andres-h commented
@cla-bot check

2022-09-03 10:07 UTC, andres-h commented
@cla-bot check

2022-09-18 16:31 UTC, luca-s commented
This should now be ready unless more changes are required from your side.

2022-09-19 09:25 UTC, gempa-jabe commented
Please rebase your branch.

2022-09-19 09:32 UTC, merged